import type { Metadata } from "next";
import localFont from "next/font/local";
import Link from "next/link";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <nav>
          <Link href="/01-build-time">01 Build Time</Link>
          <Link href="/02-dynamic-data">02 Dynamic Data</Link>
          <Link href="/03-nesting">03 Nesting</Link>
          <Link href="/04-interactivity">04 Interactivity</Link>
          <Link href="/05-async-components">05 Async Components</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
