import type { Metadata } from "next";
import localFont from "next/font/local";
import Link from "next/link";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <nav>
          <Link href="/01-server-action">
            01 Server Action (Server Component)
          </Link>
          <Link href="/02-server-action-in-client-component">
            02 Server Action in Client Component
          </Link>
          <Link href="/03-server-form-action">03 Server Form Action</Link>
          <Link href="/04-server-form-action-with-useActionState">
            04 Server Form Action with useActionState
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
